# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_name', models.CharField(max_length=50)),
                ('txn_date', models.DateField()),
                ('value_date', models.DateField()),
                ('description', models.CharField(max_length=256)),
                ('debit', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('account_no', models.CharField(max_length=25)),
                ('branch', models.CharField(max_length=25)),
                ('ifsc', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statement.User'),
        ),
    ]
