# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statements',
            new_name='Statement',
        ),
    ]
